[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

# Optional: remove if you don't use Netlify Functions
# functions = "client/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
